version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: eventapi-postgres
    environment:
      POSTGRES_DB: eventapi
      POSTGRES_USER: alveskz
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eventapi-network

volumes:
  postgres_data:

networks:
  eventapi-network:
    driver: bridge